project_name: cameradar
dist: dist/cameradar

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download

builds:
  - binary: cameradar
    main: ./cmd/cameradar
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  skip: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md